# Generated by Django 4.2.7 on 2023-12-06 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0008_alter_addresscoordinates_coordinates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='coordinates_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса координат'),
        ),
    ]
